name: learnflutter
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # ✅ Compatible with Dart 3.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fontg
      fonts:
        - asset: assets/fonts/PlaywriteMXGuides-Regular.ttf
